#
# (c) Copyright 2015-2017 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017-2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
# Tasks

# install wsgi Apache module
- name: OPS-WEB | install | Install dependencies
  become: yes
  package:
    state: present
    name: "{{ item }}"
  with_items: ops_console_packages

- name: Enable wsgi module in apache
  command: a2enmod wsgi
  register: ops_console_mod_enable_result
  changed_when: '"already enabled" not in ops_console_mod_enable_result.stdout'

- name: OPS-WEB | install | Create BLL Group
  group:
    name: "{{ ops_console_os_group }}"
    state: present

- name: OPS-WEB | install | Create BLL User
  user:
    name: "{{ ops_console_os_user }}"
    group: "{{ ops_console_os_group }}"
    createhome: no
    shell: /usr/sbin/nologin
    home: "{{ ops_console_home_dir }}"
  ignore_errors: yes

# NOTE: Matching the creation of home dir with opsconsole RPM package
# python-ardana-opsconsole-server
- name: OPS-WEB | install | Add user home
  become: yes
  file:
    path: "{{ ops_console_home_dir }}"
    state: directory
    owner: "{{ ops_console_os_user }}"
    group: "{{ ops_console_os_group }}"
    mode: 0750

- name: OPS-WEB | install | Create logging directory
  file:
    path: "{{ ops_console_log_dir }}"
    owner: "{{ ops_console_os_user }}"
    group: "{{ ops_console_os_group }}"
    mode: 0775
    state: directory

- name: OPS-WEB | install | Create Virtual Host Error Logging File
  file:
    path: "{{ ops_console_error_log }}"
    owner: "{{ ops_console_os_user }}"
    group: "{{ ops_console_centralized_log_group }}"
    mode: 0640
    state: touch

- name: OPS-WEB | install | Create Virtual Host Access Log File
  file:
    path: "{{ ops_console_access_log }}"
    owner: "{{ ops_console_os_user }}"
    group: "{{ ops_console_centralized_log_group }}"
    mode: 0640
    state: touch

# install mysql-client
- name: OPS-WEB | install | Install dependencies (mysql-client)
  become: yes
  include: "{{ playbook_dir }}/roles/FND-MDB/tasks/install_client.yml"

- name: OPS-WEB | install | install the Ops Console service and UI (rpm)
  become: yes
  package:
    state: present
    name: "{{ item }}"
  with_items:
    - python-ardana-opsconsole-server
    - ardana-opsconsole-ui

- name: OPS-WEB | install | Create WSGI directory
  file:
    path: "{{ ops_console_wsgi_dir }}"
    owner: root
    group: root
    mode: 0775
    state: directory
