 #
# (c) Copyright 2015-2017 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- name: OPS-WEB | install | Install Transient Web Artifact Project
  install_package:
    name: ops_console_content
    service: ops-console-content
    state: present
  register: ardana_notify_opsweb_reload_required

- name: OPS-WEB | install | Find archive name
  shell: ls {{ 'ops-console-content' | jar_dir }}
  register: archive_list

- name: OPS-WEB | install | Extract Ops Console UI Web Files
  unarchive:
    dest: /var/www
    src: "{{ 'ops-console-content' | jar_dir }}/{{ item }}"
    copy: no
    owner: root
    group: root
    mode: 0775
  with_items: (archive_list.stdout).splitlines()

- name: OPS-WEB | install | Remove Transient Web Artifact Project
  install_package:
    name: ops_console_content
    service: ops-console-content
    state: absent
  register: ardana_notify_opsweb_reload_required

- name: OPS-WEB | install | Clear old web directory
  file:
    path: "{{ ops_console_web_root }}"
    state: absent

- name: OPS-WEB | install | Rename Web Directory
  command: mv /var/www/dist.stdcfg "{{ ops_console_web_root }}"

- name: OPS-WEB | install | Establish Web directory
  file:
    path: "{{ ops_console_web_root }}"
    owner: root
    group: root
    mode: 0775
    state: directory
