#
# (c) Copyright 2015-2016 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017-2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
# Start

- name: OPS-WEB | Start | Enable Ops Console virtual host (hlinux)
  command: a2ensite "{{ ops_console_site_name }}"
  register: ops_console_enable_result
  changed_when: ( ops_console_enable_result | success ) and
                ( 'already enabled' not in ops_console_enable_result.stdout )
  when: ansible_os_family == 'Debian'

- name: OPS-WEB | Start | Enable Ops Console virtual host (SUSE)
  template:
    dest: "{{ apache2_vhost_dir }}/{{ ops_console_site_name }}.conf"
    src: ops-console-apache.conf
    owner: root
    group: root
    mode: 0664
  register: ops_console_enable_result
  when: ansible_os_family == 'Suse'

- include: "{{ playbook_dir }}/roles/FND-AP2/tasks/start_reload.yml"
  vars:
    apache_reload_requested: "{{ (ardana_notify_opsweb_reload_required is defined and ardana_notify_opsweb_reload_required.changed) or ops_console_enable_result.changed }}"
    apache_restart_requested: "{{ (ops_console_mod_enable_result.changed) or
                                  (ardana_notify_opsweb_apache_config_changed is defined and
                                   ardana_notify_opsweb_apache_config_changed.changed) }}"
